module.exports = Object.freeze({
    ROLE_SUPERADMIN: 'ROLE_SUPERADMIN',
    ROLE_DEALER: 'ROLE_DEALER',
    ROLE_ADMIN: 'ROLE_ADMIN',
    ROLE_DELIVERYBOY: ' ROLE_DELIVERYBOY',
    ROLE_USER: ' ROLE_USER'
    // ROLE_ADMIN : 'ROLE_ADMIN',
    // ROLE_DBA : 'ROLE_DBA'
});